name: 'Git Secret Protector Action'
description: 'Decrypts secrets in a protected repository using git-secret-protector.'
author: 'Duc Duong <duc.duong@c0x12c.com>'

branding:
  icon: unlock
  color: green

inputs:
  filter:
    description: 'The filter name to use with git-secret-protector.'
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/c0x12c/gh-actions-git-secret-protector:1.0'
  entrypoint: '/main.sh'
  post-entrypoint: '/post.sh'
  args:
    - ${{ inputs.filter }}
